pipeline {

  agent {
    node { label 'workstation' }
  }

  parameters {
    string(name: 'APPLY_ENV', defaultValue: 'dev', description: 'On which env you want to run?')
  }

  options {
    ansiColor('xterm')
  }

    stages {

      stage('Terraform Init') {
        steps {
          sh '''
            cd mutable/env-${APPLY_ENV}
            terraform init
          '''
        }
      }

      stage('Terraform Plan') {
        steps {
          sh '''
            cd mutable/env-${APPLY_ENV}
            terraform plan
          '''
        }
      }

      stage('Terraform Apply') {
        steps {
          sh '''
            cd mutable/env-${APPLY_ENV}
            terraform apply -auto-approve
          '''
        }
      }

    }

}

//